version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskbot_pg
    environment:
      POSTGRES_DB: ${PG_DBNAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

#  rabbitmq:
#    image: rabbitmq:3-alpine
#    container_name: rabbitmq
#    hostname: rabbitmq
#    restart: unless-stopped
#    ports:
#      - "5672:5672"
#    environment:
#      - RABBITMQ_USER=${RABBITMQ_USER}
#      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
#    healthcheck:
#      test: rabbitmq-diagnostics -q ping
#      interval: 30s
#      timeout: 10s
#      retries: 3

  bot:
    image: task-bot:latest
    container_name: task-bot
    build: .
    command: python bot.py
    depends_on:
      - postgres
      #- rabbitmq
    restart: unless-stopped
    volumes:
      - ./media_storage:/media_storage
      - whisper_cache:/root/.cache/whisper
    environment:
      - TOKEN=${TOKEN}
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DBNAME=${PG_DBNAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - LOCAL_PATH=${LOCAL_PATH}

volumes:
  postgres_data:
  whisper_cache:
  #rabbitmq_data: